set nocompatible        " be iMproved, required
filetype off            " required
set ls=2                " allways show status line
set tabstop=4           " numbers of spaces of tab character
set shiftwidth=4        " numbers of spaces to (auto)indent
set scrolloff=3         " keep 3 lines when scrolling
set showcmd             " display incomplete commands
set hlsearch            " highlight searches
set incsearch           " do incremental searching
set ruler               " show the cursor position all the time
set visualbell t_vb=    " turn off error beep/flash
set novisualbell        " turn off visual bell
set nobackup            " do not keep a backup file
"set number             " show line numbers
set ignorecase          " ignore case when searching
set title               " show title in console title bar
set ttyfast             " smoother changes
set encoding=utf8

if has("gui_macvim")
	syntax enable
	set background=dark
	colorscheme solarized
	set guifont=Source\ Code\ Pro:h20

	let g:solarized_termtrans=1
	let g:solarized_termcolors=256
	let g:solarized_contrast="high"
	let g:solarized_visibility="high"
endif
