" General
" https://vimconfig.com/
" https://dougblack.io/words/a-good-vimrc.html
" https://www.linode.com/docs/tools-reference/tools/introduction-to-vim-customization/

"set number         " show line numbers
"set cursorline      " highlight current line
set linebreak	    " Break lines at word (requires Wrap lines)
set showbreak=+++   " Wrap-broken line prefix
set textwidth=100   " Line wrap (number of cols)
set showmatch	    " Highlight matching brace
set errorbells	    " Beep or flash screen on errors
set visualbell	    " Use visual bell (no beeping)

set hlsearch        " highlight searches
set smartcase	    " Enable smart-case search
set ignorecase      " ignore case when searching
set incsearch       " do incremental searching

set autoindent	    " Auto-indent new lines
set shiftwidth=4    " numbers of spaces to (auto)indent
set smartindent	    " Enable smart-indent
set smarttab	    " Enable smart-tabs
set softtabstop=4   " Number of spaces per Tab

set ruler           " show the cursor position all the time
set showtabline=2   " Show tab bar

set undolevels=1000	        " Number of undo levels
set backspace=indent,eol,start	" Backspace behaviour
 
set laststatus=2                " allways show status line
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]\ [BUFFER=%n]\ %{strftime('%c')}

set tabstop=4           " numbers of spaces of tab character
set scrolloff=3         " keep 3 lines when scrolling
"set visualbell t_vb=    " turn off error beep/flash
"set novisualbell        " turn off visual bell
set nobackup            " do not keep a backup file
"set title               " show title in console title bar
set ttyfast             " Speed up scrolling in Vim

set foldenable          " enable folding
set foldlevelstart=10   " open most folds by default
set foldnestmax=10      " 10 nested fold max


syntax on            " enable syntax processing
colorscheme desert   " awesome colors(desert,delek) => /usr/share/vim/vim80/colors
